# Generated by Django 3.0.1 on 2021-09-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210923_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner_name',
            field=models.CharField(default='Adebayo Car', max_length=100, null=True),
        ),
    ]
